/// English texts, by their Russian originals (the keys are the literals in the code).
/// Generated from the code's strings; edit the values, keep the keys exactly as in the code.
enum English {
    static let strings: [String: String] = [
        " (свёрнуто)": " (minimized)",
        "Новое окно": "New Window",
        "Рабочий стол": "Desktop",
        "Загрузки": "Downloads",
        "Настройки…": "Settings…",
        "Проверить обновления…": "Check for Updates…",
        "Выйти из WinEx (вернуть Finder)": "Quit WinEx (Bring Back Finder)",
        "Этот Mac": "This Mac",
        "Сеть": "Network",
        "Корзина": "Trash",
        "Результаты поиска «%@»": "Search Results for “%@”",
        "Предыдущие папки": "Previous Folders",
        "Другие папки": "Other Folders",
        "Нет вложенных папок": "No Subfolders",
        "Создать": "New",
        "Создать папку или документ": "New folder or document",
        "Вырезать (⌘X)": "Cut (⌘X)",
        "Копировать (⌘C)": "Copy (⌘C)",
        "Вставить (⌘V)": "Paste (⌘V)",
        "Переименовать": "Rename",
        "Поделиться": "Share",
        "Удалить (⌘⌫)": "Delete (⌘⌫)",
        "Сортировать": "Sort",
        "Порядок файлов": "File order",
        "Просмотреть": "View",
        "Вид": "View",
        "Другие команды": "More commands",
        "Вырезать": "Cut",
        "Копировать": "Copy",
        "Переим.": "Rename",
        "Удалить": "Delete",
        "Открыть": "Open",
        "Показать содержимое пакета": "Show Package Contents",
        "Показать оригинал": "Show Original",
        "Открыть в новой вкладке": "Open in New Tab",
        "Открыть в новом окне": "Open in New Window",
        "Копировать путь": "Copy Path",
        "Дублировать": "Duplicate",
        "Создать псевдоним": "Make Alias",
        "Сжать «%@»": "Compress “%@”",
        "объект": "item",
        "объекта": "items",
        "объектов": "items",
        "Сжать %@ %@": "Compress %@ %@",
        "Распаковать": "Extract",
        "Настроить папку…": "Customize Folder…",
        "Свойства": "Properties",
        " (по умолчанию)": " (default)",
        "Выбрать другую программу…": "Choose Another App…",
        "Открыть с помощью": "Open With",
        "Выберите программу": "Choose an App",
        "Папку": "Folder",
        "Новая папка": "New Folder",
        "Текстовый документ": "Text Document",
        "Новый текстовый документ.txt": "New Text Document.txt",
        "Документ RTF": "RTF Document",
        "Новый документ RTF.rtf": "New RTF Document.rtf",
        "Документ Markdown": "Markdown Document",
        "Новый документ Markdown.md": "New Markdown Document.md",
        "Документ Microsoft Word": "Microsoft Word Document",
        "Новый документ Microsoft Word.docx": "New Microsoft Word Document.docx",
        "Лист Microsoft Excel": "Microsoft Excel Worksheet",
        "Новый лист Microsoft Excel.xlsx": "New Microsoft Excel Worksheet.xlsx",
        "Презентация Microsoft PowerPoint": "Microsoft PowerPoint Presentation",
        "Новая презентация Microsoft PowerPoint.pptx": "New Microsoft PowerPoint Presentation.pptx",
        "Извлечь «%@»": "Eject “%@”",
        "Упорядочить значки автоматически": "Auto Arrange Icons",
        "Выровнять значки по сетке": "Align Icons to Grid",
        "Отображать значки рабочего стола": "Show Desktop Icons",
        "Сортировка": "Sort By",
        "Обновить": "Refresh",
        "Вставить": "Paste",
        "Открыть «Рабочий стол» в WinEx": "Open “Desktop” in WinEx",
        "Обои…": "Wallpaper…",
        "Настройки WinEx…": "WinEx Settings…",
        "Крупные значки": "Large Icons",
        "Обычные значки": "Medium Icons",
        "Мелкие значки": "Small Icons",
        "Имя": "Name",
        "Размер": "Size",
        "Тип элемента": "Item Type",
        "Дата изменения": "Date Modified",
        "Устройства и диски": "Devices and Drives",
        "Сетевые расположения": "Network Locations",
        "%@ свободно из %@": "%@ free of %@",
        "Назад (⌘[)": "Back (⌘[)",
        "Вперёд (⌘])": "Forward (⌘])",
        "Вверх (⌘↑)": "Up (⌘↑)",
        "Обновить (⌘R)": "Refresh (⌘R)",
        "Настройки": "Settings",
        "Путь к папке": "Folder path",
        "Скрытые файлы": "Hidden Files",
        "Панель команд": "Command Bar",
        "Показать": "Show",
        "Применить ко всем папкам": "Apply to All Folders",
        "Сжать в ZIP-файл": "Compress to ZIP File",
        "Добавить в избранное": "Add to Favorites",
        "Скопировать путь": "Copy Path",
        "Выделить всё": "Select All",
        "Снять выделение": "Select None",
        "Обратить выделение": "Invert Selection",
        "Параметры": "Options",
        "Таблица": "Details",
        "Значки": "Icons",
        "Поиск на Mac": "Search This Mac",
        "Поиск: %@": "Search: %@",
        "Копировать адрес": "Copy Address",
        "Копировать адрес как URL": "Copy Address as URL",
        "Изменить адрес": "Edit Address",
        "Очистить историю переходов": "Clear Browsing History",
        "Где искать": "Where to Search",
        "В этой папке и вложенных": "This Folder and Subfolders",
        "На всём Mac": "Entire Mac",
        "Что искать": "What to Search",
        "Имена и содержимое": "Names and Contents",
        "Только имена": "Names Only",
        "Недавние запросы": "Recent Searches",
        "Нет недавних запросов": "No Recent Searches",
        "Очистить недавние": "Clear Recents",
        "Поиск": "Search",
        "Архив": "Archive",
        "элемента": "items",
        "элементов": "items",
        "Сжатие %@ %@ в «%@»": "Compressing %@ %@ into “%@”",
        "Распаковка «%@» в ": "Extracting “%@” to ",
        " — не удалось": " — failed",
        "%@ псевдоним": "%@ alias",
        "Не удалось найти оригинал «%@»": "Couldn’t find the original of “%@”",
        "Возможно, он удалён или находится на отключённом диске.": "It may have been deleted or be on a disconnected drive.",
        "Подготовка…": "Preparing…",
        "%@% выполнено": "%@% complete",
        "Отмена": "Cancel",
        "Изображение": "Image",
        "Размеры": "Dimensions",
        "%@ × %@ пикселей": "%@ × %@ pixels",
        " (%.1f Мп)": " (%.1f MP)",
        "Разрешение": "Resolution",
        "%@ точек на дюйм": "%@ dots per inch",
        "Глубина цвета": "Color Depth",
        "%@ бит на канал": "%@ bits per channel",
        "Цвет": "Color",
        "Прозрачность": "Transparency",
        "Есть": "Yes",
        "Нет": "No",
        "Кадров": "Frames",
        "Съёмка": "Camera",
        "Дата съёмки": "Date Taken",
        "Камера": "Camera",
        "Объектив": "Lens",
        "%.1f с": "%.1f s",
        "1/%@ с": "1/%@ s",
        "Экспозиция": "Exposure",
        "Фокусное расстояние": "Focal Length",
        "%.0f мм": "%.0f mm",
        " (%@ мм экв.)": " (%@ mm equiv.)",
        "Вспышка": "Flash",
        "Сработала": "Fired",
        "Не сработала": "Did not fire",
        "Место": "Location",
        "Запись": "Recording",
        "Длительность": "Duration",
        "Название": "Title",
        "Исполнитель": "Artist",
        "Альбом": "Album",
        "Дата": "Date",
        "Видео": "Video",
        "Размер кадра": "Frame Size",
        "Частота кадров": "Frame Rate",
        "%.0f к/с": "%.0f fps",
        "%.2f к/с": "%.2f fps",
        "Кодек": "Codec",
        "Битрейт": "Bit Rate",
        "Звук": "Audio",
        "Частота": "Sample Rate",
        "%.1f кГц": "%.1f kHz",
        "Каналы": "Channels",
        "Моно": "Mono",
        "Стерео": "Stereo",
        "%.1f Мбит/с": "%.1f Mbit/s",
        "%.0f кбит/с": "%.0f kbit/s",
        "Документ": "Document",
        "Страниц": "Pages",
        "Размер страницы": "Page Size",
        "%@ × %@ мм": "%@ × %@ mm",
        "Заголовок": "Title",
        "Автор": "Author",
        "Создано в": "Created With",
        "Программа PDF": "PDF Producer",
        "Версия PDF": "PDF Version",
        "Защита": "Protection",
        "Требуется пароль": "Password required",
        "Зашифрован": "Encrypted",
        "Текст": "Text",
        "Строк": "Lines",
        "Слов": "Words",
        "Символов": "Characters",
        "Кодировка": "Encoding",
        "Программа": "Application",
        "Версия": "Version",
        "Идентификатор": "Identifier",
        "Процессоры": "Processors",
        "Нужна macOS": "Requires macOS",
        " или новее": " or later",
        "Авторские права": "Copyright",
        "Загрузка": "Download",
        "Откуда": "Downloaded From",
        "Страница": "Page",
        "Огромные значки": "Extra Large Icons",
        "Список": "List",
        "Плитка": "Tiles",
        "Введите хотя бы 2 символа для поиска на всём Mac": "Type at least 2 characters to search the entire Mac",
        "Сервер (%@)": "Server (%@)",
        "WinEx нужен «Полный доступ к диску», чтобы показать Корзину (правый клик → открыть настройки)": "WinEx needs Full Disk Access to show the Trash (right-click → open settings)",
        "диск": "drive",
        "диска": "drives",
        "дисков": "drives",
        "%@ + папки…": "%@ + folders…",
        "размер считается…": "calculating size…",
        "Нет доступа к Корзине": "No Access to the Trash",
        "macOS показывает Корзину только программам с «Полным доступом к диску». Включите WinEx в настройках и нажмите «Закрыть и открыть снова». После пересборки WinEx доступ нужно дать заново.": "macOS shows the Trash only to apps with Full Disk Access. Turn WinEx on in the settings and click “Quit & Reopen”. After WinEx is rebuilt, access has to be granted again.",
        "Открыть настройки «Полный доступ к диску»…": "Open Full Disk Access Settings…",
        "Нет доступа к папке": "No Access to This Folder",
        "Ничего не найдено": "Nothing Found",
        "Серверы не найдены": "No Servers Found",
        "Подключиться к серверу по адресу — ⌘K.": "Connect to a server by its address — ⌘K.",
        "Нет файлов с этим тегом": "No Files with This Tag",
        "Корзина пуста": "The Trash Is Empty",
        "Эта папка пуста": "This Folder Is Empty",
        "элемент": "item",
        "Найдено: %@": "Found: %@",
        " (показаны самые подходящие)": " (showing the best matches)",
        "    Поиск…": "    Searching…",
        "    Выбрано: %@": "    Selected: %@",
        "Нет доступа: %@": "No access: %@",
        "Не удалось вернуть: %@": "Couldn’t put back: %@",
        "Для этих объектов не сохранилось исходное расположение.": "The original location of these items wasn’t recorded.",
        "Подключиться": "Connect",
        "Вернуть": "Put Back",
        "Удалить навсегда": "Delete Immediately",
        "Быстрый просмотр": "Quick Look",
        "Очистить Корзину": "Empty Trash",
        "Показать в папке": "Show in Folder",
        "Копировать путь к папке": "Copy Folder Path",
        "Дополнительно": "More",
        "По возрастанию": "Ascending",
        "По убыванию": "Descending",
        "Столбец по размеру содержимого": "Size Column to Fit",
        "Все столбцы по размеру содержимого": "Size All Columns to Fit",
        "Очистить": "Empty",
        "Удалить навсегда всё, что лежит в Корзине": "Permanently delete everything in the Trash",
        "Дата создания": "Date Created",
        "Дата добавления": "Date Added",
        "Тип": "Type",
        "Теги": "Tags",
        "Папка": "Folder",
        "Нельзя поместить папку «%@» в саму себя.": "Can’t put the folder “%@” inside itself.",
        "Не удалось обработать «%@»": "Couldn’t process “%@”",
        "Пропустить": "Skip",
        "Копирование %@": "Copying %@",
        "Перемещение %@": "Moving %@",
        "Удаление %@": "Deleting %@",
        " из ": " from ",
        " в Корзину": " to the Trash",
        " в ": " to ",
        "Приостановить": "Pause",
        "Имя:": "Name:",
        "Осталось времени:": "Time remaining:",
        "Осталось элементов:": "Items remaining:",
        "Ожидание ответа…": "Waiting for your answer…",
        "Приостановлено — %@%": "Paused — %@%",
        "Продолжить": "Resume",
        "Скорость: %@/с": "Speed: %@/s",
        "Вычисление…": "Calculating…",
        "около ": "about ",
        "Отмена…": "Cancelling…",
        "Меньше подробностей": "Fewer Details",
        "Больше подробностей": "More Details",
        "Замена или пропуск файлов": "Replace or Skip Files",
        "таким же именем": "the same name",
        "такими же именами": "the same names",
        "В папке назначения уже есть %@ %@ с %@": "The destination already has %@ %@ with %@",
        "Заменить файлы в папке назначения": "Replace the files in the destination",
        "Пропустить эти файлы": "Skip these files",
        "Решить для каждого файла": "Decide for each file",
        " и ещё %@": " and %@ more",
        "Выберите, что сделать с каждым элементом": "Choose what to do with each item",
        "Новый: %@\nВ папке: %@": "New: %@\nIn the folder: %@",
        "Заменить": "Replace",
        "Оставить оба": "Keep Both",
        "папка": "folder",
        "%@, изменён %@": "%@, modified %@",
        "Переименование": "Rename",
        "Перемещение": "Move",
        "Копирование": "Copy",
        "Перемещение в Корзину": "Move to Trash",
        "Создание папки": "New Folder",
        "Создание файла": "New File",
        "Изменение тегов": "Tag Change",
        "Люди": "People",
        "Животные и природа": "Animals & Nature",
        "Работа и учёба": "Work & Study",
        "Медиа": "Media",
        "Техника": "Tech",
        "Места и транспорт": "Places & Travel",
        "Покупки и деньги": "Shopping & Money",
        "Эмодзи": "Emoji",
        "Снять теги": "Remove Tags",
        "Снять все теги": "Remove All Tags",
        "Добавить тег": "Add Tag",
        "Добавить тег…": "Add Tag…",
        "Новый тег": "New Tag",
        "Название тега": "Tag name",
        "Добавить": "Add",
        "Отменить": "Cancel",
        "Выключено": "Off",
        "⌘E — как Win+E": "⌘E — like Win+E",
        "Поиск «%@»": "Search “%@”",
        "Теги: %@": "Tags: %@",
        "Результаты поиска «%@» ": "Search results for “%@” ",
        "на всём Mac": "on the entire Mac",
        "в «%@»": "in “%@”",
        "Выйти из WinEx": "Quit WinEx",
        "Файл": "File",
        "Новая вкладка": "New Tab",
        "Закрыть вкладку": "Close Tab",
        "Сжать": "Compress",
        "Найти": "Find",
        "Переместить в корзину": "Move to Trash",
        "Правка": "Edit",
        "Повторить": "Redo",
        "Показывать скрытые файлы": "Show Hidden Files",
        "Переход": "Go",
        "Назад": "Back",
        "Вперёд": "Forward",
        "Вверх": "Enclosing Folder",
        "Перейти к пути…": "Go to Path…",
        "Подключиться к серверу…": "Connect to Server…",
        "Следующая вкладка": "Next Tab",
        "Предыдущая вкладка": "Previous Tab",
        "Окно": "Window",
        "Свернуть": "Minimize",
        "Масштаб": "Zoom",
        "Все окна — на передний план": "Bring All to Front",
        "Пробел": "Space",
        "Очистить Корзину?": "Empty the Trash?",
        "%@ объектов": "%@ items",
        "Удалить %@ навсегда?": "Delete %@ permanently?",
        "Это действие нельзя отменить.": "You can’t undo this action.",
        "Не удалось подключиться к «%@».": "Couldn’t connect to “%@”.",
        "Подключение к серверу": "Connect to Server",
        "Например: smb://NAS.local или afp://192.168.1.10/Share": "For example: smb://NAS.local or afp://192.168.1.10/Share",
        "Вычисляется…": "Calculating…",
        "Свойства: %@": "Properties: %@",
        "Свойства: %@ %@": "Properties: %@ %@",
        "Общие": "General",
        "Подробно": "Details",
        "Доступ": "Access",
        "файл": "file",
        "файла": "files",
        "файлов": "files",
        "папки": "folders",
        "папок": "folders",
        "Разные типы": "Various types",
        "Файловая система": "File System",
        "Изменить…": "Change…",
        "Открывается в": "Opens With",
        "Разные папки": "Various folders",
        "Расположение": "Location",
        "На диске": "On Disk",
        "Содержит": "Contains",
        "Создан": "Created",
        "Изменён": "Modified",
        "Открыт": "Opened",
        "Добавлен": "Added",
        "Даты": "Dates",
        "Атрибуты": "Attributes",
        "Только чтение": "Read Only",
        "Защищено от изменения и удаления": "Protected from changes and deletion",
        "Скрытый": "Hidden",
        "Не виден, пока скрытые файлы не показаны": "Not visible unless hidden files are shown",
        "Собираю сведения…": "Gathering details…",
        "Других сведений об этом объекте нет": "No other details about this item",
        "Владелец": "Owner",
        " (вы)": " (you)",
        "Группа": "Group",
        "Чтение и запись": "Read & Write",
        "Только запись": "Write Only",
        "Нет доступа": "No Access",
        ", запуск": ", run",
        " (без входа в папку)": " (can’t open the folder)",
        "Права": "Permissions",
        "Остальные": "Everyone Else",
        "Код": "Code",
        "читать": "read",
        "изменять": "change",
        "удалять": "delete",
        "Для вас": "For You",
        "Можно": "You Can",
        "Ничего": "Nothing",
        "Ёмкость ": "Capacity ",
        "Свободно ": "Free ",
        "байт": "bytes",
        "байта": "bytes",
        "Не назначено": "Not set",
        "Открывать файлы «%@» в программе": "Open “%@” files with",
        "Показывать в боковом меню:": "Show in the sidebar:",
        "Избранное": "Favorites",
        "Перетащите папку в «Избранное» боковой панели, чтобы закрепить её; перетаскиванием меняется и порядок.": "Drag a folder into the sidebar’s Favorites to pin it; dragging also changes the order.",
        "Места": "Locations",
        "Какие именно теги показывать — во вкладке «Теги».": "Which tags to show — on the Tags tab.",
        "Без цвета": "No Color",
        "Серый": "Gray",
        "Зелёный": "Green",
        "Лиловый": "Purple",
        "Синий": "Blue",
        "Жёлтый": "Yellow",
        "Красный": "Red",
        "Оранжевый": "Orange",
        "Сбоку": "Sidebar",
        "Тег": "Tag",
        "Избранный": "Favorite",
        "Показывать в боковом меню": "Show in the sidebar",
        "Цветной ряд в контекстном меню (как в Finder)": "The colored row in the context menu (as in Finder)",
        "Удалить тег": "Delete Tag",
        "«Сбоку» — показывать тег в боковом меню. «Избранный» — кружок в контекстном меню файлов; этот список общий с Finder. Переименование и смена цвета применяются ко всем файлам с тегом.": "“Sidebar” — show the tag in the sidebar. “Favorite” — a circle in the files’ context menu; this list is shared with Finder. Renaming and recoloring apply to every file with the tag.",
        "Оттенять папки цветом тега": "Tint folders with the tag color",
        "Новый тег %@": "New Tag %@",
        "Удалить тег «%@»?": "Delete the tag “%@”?",
        "Тег будет снят со всех файлов, у которых он есть.": "The tag will be removed from every file that has it.",
        "«Открыть в терминале» в контекстном меню": "“Open in Terminal” in the context menu",
        "Панель команд под адресной строкой": "Command bar under the address bar",
        "Открывать WinEx при входе в систему": "Open WinEx at login",
        "Открыть «Объекты входа»…": "Open Login Items…",
        "Использовать WinEx вместо Finder": "Use WinEx instead of Finder",
        "Сбросить рабочий стол как в Finder…": "Reset the Desktop as in Finder…",
        "Клавиши как в Windows": "Windows keys",
        "Проверять обновления автоматически": "Check for updates automatically",
        "Домашняя папка": "Home Folder",
        "Документы": "Documents",
        "Настройки WinEx": "WinEx Settings",
        "Основные": "General",
        "Боковое меню": "Sidebar",
        "Клавиатура": "Keyboard",
        "Обновления": "Updates",
        "Новые окна открываются в:": "New windows open in:",
        "Окно WinEx из любой программы:": "WinEx window from any app:",
        "Показ:": "Show:",
        "Терминал:": "Terminal:",
        "Для папки — она сама, для файла — его папка; на пустом месте — открытая папка или рабочий стол.": "A folder opens as is, a file — its folder; on an empty spot — the open folder or the desktop.",
        "Запуск:": "Startup:",
        "Когда WinEx заменяет Finder:\n• рабочий стол рисует WinEx, папки с него открываются в WinEx;\n• «Показать в Finder» в других программах показывает файл в WinEx;\n• папки, которые другие программы открывают сами, по-прежнему открываются в Finder — macOS не даёт сменить программу для папок;\n• «Выйти» в строке меню возвращает всё Finder.": "When WinEx replaces Finder:\n• WinEx draws the desktop, and folders on it open in WinEx;\n• “Show in Finder” in other apps shows the file in WinEx;\n• folders that other apps open by themselves still open in Finder — macOS doesn’t let you change the app for folders;\n• “Quit” in the menu bar gives everything back to Finder.",
        "Рабочий стол:": "Desktop:",
        "Рабочий стол и «Показать в Finder» переходят к WinEx. «Выйти» в строке меню возвращает Finder.": "The desktop and “Show in Finder” go to WinEx. “Quit” in the menu bar brings Finder back.",
        "Значки:": "Icons:",
        "Расставить значки, их размер и сортировку так, как у Finder.": "Arrange the icons, their size and sorting the way Finder has them.",
        "Клавиши:": "Keys:",
        "Выключено — как в Finder: Enter переименовывает, ⌘↓ или ⌘O открывают, ⌘↑ — вверх.": "Off — as in Finder: Return renames, ⌘↓ or ⌘O open, ⌘↑ goes up.",
        "С «Клавишами как в Windows»": "With “Windows keys”",
        "открыть": "open",
        "переименовать": "rename",
        "на уровень выше": "up one level",
        "назад / вперёд": "back / forward",
        "поиск": "search",
        "адресная строка": "address bar",
        "обновить": "refresh",
        "полный экран": "full screen",
        "в Корзину": "to the Trash",
        "удалить навсегда": "delete permanently",
        "контекстное меню": "context menu",
        "Всегда": "Always",
        "следующая / предыдущая вкладка": "next / previous tab",
        "вкладка по номеру": "tab by number",
        "⌘ + перетащить": "⌘ + drag",
        "переместить": "move",
        "⌥ + перетащить": "⌥ + drag",
        "копировать": "copy",
        "⌘⌥ + перетащить": "⌘⌥ + drag",
        "создать псевдоним": "make an alias",
        "Полный доступ к диску:": "Full Disk Access:",
        "Проверить сейчас": "Check Now",
        "Страница релизов…": "Releases Page…",
        " (своя сборка)": " (own build)",
        "Версия:": "Version:",
        "Обновления:": "Updates:",
        "Своя сборка сама не обновляется — только по кнопке «Проверить сейчас».": "An own build doesn’t update by itself — only with “Check Now”.",
        "Раз в сутки WinEx проверяет новые версии и предлагает обновиться. Разрешения сохраняются.": "Once a day WinEx looks for new versions and offers to update. Permissions are kept.",
        "macOS ждёт разрешения в «Системные настройки ▸ Основные ▸ Объекты входа».": "macOS is waiting for approval in System Settings ▸ General ▸ Login Items.",
        "Без окна: значок в строке меню и, если WinEx заменяет Finder, рабочий стол.": "No window: an icon in the menu bar and, if WinEx replaces Finder, the desktop.",
        "Выдан": "Granted",
        "Не выдан": "Not granted",
        "WinEx видит Корзину, Рабочий стол, Документы, Загрузки и сетевые диски без отдельных вопросов.": "WinEx sees the Trash, Desktop, Documents, Downloads and network drives without asking each time.",
        "Без него Корзина не открывается, а про Рабочий стол, Документы, Загрузки и сетевые диски macOS спрашивает отдельно. Включите WinEx в списке и нажмите «Закрыть и открыть снова».": "Without it the Trash doesn’t open, and macOS asks separately about Desktop, Documents, Downloads and network drives. Turn WinEx on in the list and click “Quit & Reopen”.",
        "Это сочетание занято другой программой — выберите другое.": "This shortcut is taken by another app — choose another one.",
        "Из любой программы. В некоторых программах ⌘E — «Искать выделенное».": "From any app. In some apps ⌘E is “Use Selection for Find”.",
        "Из любой программы, как Win+E в Windows.": "From any app, like Win+E in Windows.",
        "Другая папка…": "Other Folder…",
        "Сбросить рабочий стол WinEx?": "Reset the WinEx desktop?",
        "Значки встанут туда, где они у Finder, а размер значков и сортировка станут как в Finder. Ваша расстановка на рабочем столе WinEx будет потеряна. Файлы не изменятся.": "The icons will go where Finder has them, and the icon size and sorting will be as in Finder. Your arrangement on the WinEx desktop will be lost. Files won’t change.",
        "Сбросить": "Reset",
        "Выбрать": "Choose",
        "Другая программа…": "Other App…",
        "Терминал для «Открыть в терминале»": "Terminal for “Open in Terminal”",
        "Программы": "Applications",
        "Внутренние диски": "Internal Drives",
        "Внешние диски": "External Drives",
        "Подключённые серверы": "Connected Servers",
        "%@ на %@": "%@ on %@",
        "Убрать из боковой панели": "Remove from Sidebar",
        "Очистить Корзину…": "Empty Trash…",
        "Скрыть «%@»": "Hide “%@”",
        "Настроить боковую панель…": "Customize Sidebar…",
        "Извлечь": "Eject",
        "Новая вкладка (⌘T)": "New Tab (⌘T)",
        "Закрыть вкладку (⌘W)": "Close Tab (⌘W)",
        "Новый тег…": "New Tag…",
        "Для «%@»": "For “%@”",
        "Для %@ объектов": "For %@ items",
        "Терминал": "Terminal",
        "Открыть в Терминале": "Open in Terminal",
        "Открыть в %@": "Open in %@",
        "Не удалось проверить обновления": "Couldn’t check for updates",
        "Это своя сборка WinEx": "This is your own build of WinEx",
        "Она собрана из исходников и не заменяется релизами (последний — %@). Чтобы получать обновления автоматически, установите WinEx со страницы релизов.": "It was built from source and isn’t replaced by releases (the latest is %@). To get updates automatically, install WinEx from the releases page.",
        "Установлена последняя версия": "You’re up to date",
        "WinEx %@ — самая новая.": "WinEx %@ is the latest version.",
        "Доступна новая версия WinEx %@": "WinEx %@ is available",
        "У вас %@.": "You have %@.",
        "Обновить и перезапустить": "Update and Relaunch",
        "Позже": "Later",
        "Пропустить эту версию": "Skip This Version",
        "Не удалось обновить WinEx": "Couldn’t update WinEx",
        "Нет прав на запись в «%@». Переместите WinEx в «Программы».": "No permission to write to “%@”. Move WinEx to Applications.",
        "Загрузка WinEx %@…": "Downloading WinEx %@…",
        "Обновление не установлено": "Update not installed",
        "Новая версия подписана другим сертификатом — это может быть подделка. Скачайте WinEx вручную со страницы релизов.": "The new version is signed with a different certificate — it may be forged. Download WinEx manually from the releases page.",
        "Не удалось загрузить обновление": "Couldn’t download the update",
        " - копия": " copy",
        " - копия (%@)": " copy %@",
        "Язык:": "Language:",
        "Как в системе": "System Language",
        "«Как в системе»: русский, если macOS на русском, иначе английский.": "“System Language”: Russian if macOS is in Russian, English otherwise.",
        "В меню": "In Menu",
        "Выбрать…": "Choose…",
        "Для": "For",
        "Имя файла": "File Name",
        "Какие файлы предлагать в «Создать ▸». Свой тип — название, имя нового файла с расширением и, если нужно, файл-образец, который будет копироваться.": "Which files New ▸ offers. Your own type: a title, the new file's name with its extension and, if you like, a sample file to copy.",
        "Новый тип": "New Type",
        "Новый файл.txt": "New File.txt",
        "Образец": "Sample",
        "Расширения": "Extensions",
        "Свои программы — для каких объектов и типов файлов их предлагать; «В меню» — отдельный пункт «Открыть в …» в контекстном меню.": "Your apps — which items and file types they're offered for; “In Menu” — an “Open in …” item of its own in the context menu.",
        "Только папки": "Folders Only",
        "Только файлы": "Files Only",
        "Файл, который будет копироваться; без него создаётся пустой файл": "A file to copy; without it an empty file is created",
        "Файлы и папки": "Files and Folders",
        "любые": "any",
        "пустой": "empty",
        "Программы, которые macOS предлагает в «Открыть с помощью» (снимите флажок — не предлагать):": "Apps macOS offers in “Open With” (uncheck to leave one out):",
        "Восстановить": "Restore",
        "Восстановить настройки по умолчанию?": "Restore the default settings?",
        "Все настройки WinEx вернутся к исходным: вид папок, столбцы, боковое меню, теги, программы, язык, клавиши. Расстановка значков на рабочем столе и режим «вместо Finder» останутся. WinEx перезапустится.": "All WinEx settings go back to the defaults: folder views, columns, sidebar, tags, apps, language, keys. The desktop icon arrangement and the “instead of Finder” mode stay. WinEx will restart.",
        "Все настройки WinEx: вид, боковое меню, теги, программы, рабочий стол…": "Every WinEx setting: views, sidebar, tags, apps, desktop…",
        "Загрузить": "Load",
        "Загрузить из файла…": "Load from File…",
        "Загрузить настройки из «%@»?": "Load the settings from “%@”?",
        "Настройки:": "Settings:",
        "По умолчанию…": "Defaults…",
        "Сохранены %@.": "Saved %@.",
        "Сохранить в файл…": "Save to File…",
        "Сохранить все настройки в файл (например, перед переустановкой или для другого Mac), загрузить их обратно или вернуть исходные.": "Save every setting to a file (before reinstalling, or for another Mac), load them back, or go back to the defaults.",
        "Текущие настройки будут заменены. WinEx перезапустится с теми же окнами.": "The current settings will be replaced. WinEx will restart with the same windows.",
        "Файл настроек WinEx": "A WinEx settings file",
        "Это не файл настроек WinEx": "This isn’t a WinEx settings file",
        "Enter — открыть, F2 — переименовать, Backspace — наверх, Delete — в Корзину": "Return opens, F2 renames, Backspace goes up, Delete moves to the Trash",
        "Enter — переименовать, ⌘↓ — открыть, ⌘↑ — наверх": "Return renames, ⌘↓ opens, ⌘↑ goes up",
        "Finder остаётся; WinEx — обычная программа со своими окнами.": "Finder stays; WinEx is a regular app with its own windows.",
        "WinEx вместо Finder?": "WinEx instead of Finder?",
        "«Выйти» в строке меню всегда возвращает всё Finder.": "“Quit” in the menu bar always gives everything back to Finder.",
        "Без окна: значок в строке меню": "No window: an icon in the menu bar",
        "Вид запоминается для каждой папки; это — вид по умолчанию.": "Each folder remembers its view; this is the default one.",
        "Вид папок": "Folder View",
        "Вид папок по умолчанию:": "Default folder view:",
        "Вкладки, адресная строка и панель команд, как в Windows 11": "Tabs, an address bar and a command bar, as in Windows 11",
        "Всё можно поменять в «Настройки» (⌘,). Мастер можно пройти снова оттуда же.": "Everything can be changed in Settings (⌘,) — and the assistant can be run again from there.",
        "Готово!": "All Set!",
        "Далее": "Next",
        "Добро пожаловать в WinEx": "Welcome to WinEx",
        "Доступ выдан": "Access granted",
        "Доступ ещё не выдан": "Access not granted yet",
        "Доступ к файлам": "Access to Files",
        "Если язык сменится, WinEx перезапустится и продолжит с этого места.": "If the language changes, WinEx restarts and continues from here.",
        "Запуск": "Startup",
        "Как в Finder": "Like Finder",
        "Как в Windows": "Like Windows",
        "Клавиши": "Keys",
        "Клавиши Windows и вызов окна из любой программы": "Windows keys and a window from any app",
        "Мастер настройки WinEx": "WinEx Setup Assistant",
        "Мастер настройки…": "Setup Assistant…",
        "Начать": "Get Started",
        "Нужно для рабочего стола WinEx после перезагрузки": "Needed for the WinEx desktop after a restart",
        "Окна и рабочий стол": "Windows and the Desktop",
        "Окно WinEx из любой программы (как Win+E):": "WinEx window from any app (like Win+E):",
        "Открыть WinEx": "Open WinEx",
        "Перетащите папку в «Избранное», чтобы закрепить": "Drag a folder into Favorites to pin it",
        "Правый щелчок — меню в стиле Windows 11": "Right-click for a Windows 11–style menu",
        "Проводник в стиле Windows для macOS. Настроим главное за минуту — всё это можно поменять потом в настройках.": "A Windows Explorer–style file manager for macOS. Let’s set up the essentials in a minute — you can change all of it later in Settings.",
        "Рабочий стол рисует WinEx, «Показать в Finder» в других программах открывает WinEx. Значки встанут как у Finder.": "WinEx draws the desktop, and “Show in Finder” in other apps opens WinEx. Icons are arranged as Finder has them.",
        "Раз в сутки; разрешения сохраняются": "Once a day; permissions are kept",
        "Русский, если macOS на русском, иначе английский": "Russian if macOS is in Russian, English otherwise",
        "С «Полным доступом к диску» открывается Корзина, а macOS не спрашивает отдельно про Рабочий стол, Документы, Загрузки и каждый сетевой диск.": "With Full Disk Access the Trash opens, and macOS doesn’t ask separately about Desktop, Documents, Downloads and every network drive.",
        "Свой рабочий стол и режим «вместо Finder»": "Its own desktop and an “instead of Finder” mode",
        "Создать, вырезать, копировать, сортировать, вид…": "New, cut, copy, sort, view…",
        "Теги, программы и боковое меню — в настройках": "Tags, apps and the sidebar — in Settings",
        "Только окна": "Windows Only",
        "Язык": "Language",
        "Запустить в Терминале": "Run in Terminal",
        "Запустить в %@": "Run in %@",
        "Включите WinEx в списке. Если его там нет — перетащите значок ниже прямо в список (или нажмите «+» и выберите WinEx). Если macOS предложит «Закрыть и открыть снова» — согласитесь: мастер продолжит с этого шага.": "Turn WinEx on in the list. If it isn’t there, drag the icon below into the list (or click “+” and choose WinEx). If macOS offers “Quit & Reopen”, accept — the assistant goes on from this step.",
        "перетащите в список": "drag into the list",
    ]
}
